In [2]:
import numpy as np
import tensorflow as tf

In [3]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
arr1.shape

(3,)

In [5]:
arr2 = np.array([[1.2,2.2],
               [3.3, 4.7]])
arr2.shape

(2, 2)

In [6]:
arr3 = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
arr3.shape

(2, 3, 2)

In [7]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [8]:
arr1 + arr1

array([2, 4, 6])

In [9]:
np.dot(arr1,arr1)

14

In [10]:
arr1 =np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[1,2],[3,4],[5,6]])
arr1, arr2

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [11]:
np.dot(arr1,arr2)

array([[22, 28],
       [22, 28]])

In [12]:
arr1 = np.array([1,2,3,4,5,6])
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.reshape(1,2,3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [17]:
arr1.sum(), arr1.mean()

(21, 3.5)

In [18]:
arr1.max(), arr1.min()

(6, 1)

In [19]:
tensor1 = tf.constant([[1,2,3],[4,5,6]])
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [20]:
np.mean(tensor1)

3.5